# Generated by Django 5.1.6 on 2025-04-07 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('employee_id', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=25)),
                ('supplier', models.CharField(max_length=100)),
                ('avg_time', models.FloatField(default=0)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.DateTimeField(blank=True, null=True)),
                ('on_time', models.BooleanField(default=False)),
                ('in_full', models.BooleanField(default=False)),
                ('number_of_items', models.IntegerField()),
                ('ft_items', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('current_stock', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('new_product', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activities', models.CharField(max_length=50)),
                ('cases', models.CharField(max_length=50)),
                ('number_cases', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('avg_time', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=25)),
                ('tpt', models.FloatField(default=0)),
                ('user', models.CharField(default='None', max_length=25)),
                ('user_type', models.CharField(default='None', max_length=25)),
                ('automatic', models.BooleanField(default=False)),
                ('rework', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.case')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('material_code', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('is_free_text', models.BooleanField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.case')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion1_order_items', to='api.inventory')),
            ],
        ),
    ]
