# Generated by Django 5.1.6 on 2025-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='case_index',
            field=models.IntegerField(default=0),
        ),
    ]
