# Generated by Django 5.1.6 on 2025-04-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity_case_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pattern', models.CharField(choices=[('Similar Value', 'Similar Value'), ('Similar Reference', 'Similar Reference'), ('Exact Match', 'Exact Match'), ('Similar Date', 'Similar Date'), ('Similar Vendor', 'Similar Vendor'), ('Multiple', 'Multiple')], max_length=50)),
                ('open', models.BooleanField(default=True)),
                ('group_id', models.CharField(max_length=50)),
                ('confidence', models.CharField(max_length=6)),
                ('description', models.CharField(default='No description', max_length=250)),
                ('payment_method', models.CharField(default='Credit Card', max_length=50)),
                ('pay_date', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.CharField(blank=True, max_length=50, null=True)),
                ('accuracy', models.IntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.case')),
            ],
        ),
    ]
